spring:
  datasource:
    url: jdbc:h2:mem:testdb
    schema:
      - classpath:schema-develop.sql
mybatis:
  type-aliases-package: com.dilsonjlrjr.mateus.estoque.model
  type-handlers-package: com.dilsonjlrjr.mateus.estoque.model.typehandler
  mapper-locations: classpath*:**/mappers/*Mapper.xml
