CREATE TABLE IF NOT EXISTS ES01FILIAL(PK01_INT_IDFILIAL INT AUTO_INCREMENT PRIMARY KEY, ES01_VARCHAR_NOME VARCHAR(200))

CREATE TABLE IF NOT EXISTS ES02PRODUTO(PK02_INT_IDPRODUTO INT AUTO_INCREMENT PRIMARY KEY, PK02_VARCHAR_NOME VARCHAR(200), FK02_01_INT_IDFILIAL INT)
ALTER TABLE ES02PRODUTO ADD FOREIGN KEY (FK02_01_INT_IDFILIAL) REFERENCES ES01FILIAL(PK01_INT_IDFILIAL)

CREATE TABLE IF NOT EXISTS ES05ESTOQUE(PK05_INT_IDESTOQUE INT AUTO_INCREMENT PRIMARY KEY, ES05_INT_QUANTIDADE INT, FK05_02_INT_IDPRODUTO INT)
ALTER TABLE ES05ESTOQUE ADD FOREIGN KEY (FK05_02_INT_IDPRODUTO) REFERENCES ES02PRODUTO(PK02_INT_IDPRODUTO)