CREATE TABLE ES01FILIAL(PK01_INT_IDFILIAL INT AUTO_INCREMENT PRIMARY KEY, ES01_VARCHAR_NOME VARCHAR(200))
CREATE TABLE ES02PRODUTO(PK02_INT_IDPRODUTO INT AUTO_INCREMENT PRIMARY KEY, PK02_VARCHAR_NOME VARCHAR(200), FK02_01_INT_IDFILIAL INT)
ALTER TABLE ES02PRODUTO ADD FOREIGN KEY (FK02_01_INT_IDFILIAL) REFERENCES ES01FILIAL(PK01_INT_IDFILIAL)